# Generated by Django 3.2.5 on 2024-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='week_plan',
            field=models.CharField(choices=[('WEEK 1', 'Week 1'), ('WEEK 2', 'Week 2'), ('WEEK 3', 'Week 3'), ('WEEK 4', 'Week 4'), ('WEEK 5', 'Week 5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='scheduled_week',
            field=models.CharField(choices=[('WEEK 1', 'Week 1'), ('WEEK 2', 'Week 2'), ('WEEK 3', 'Week 3'), ('WEEK 4', 'Week 4'), ('WEEK 5', 'Week 5')], max_length=20),
        ),
    ]
