# Generated by Django 3.2.5 on 2024-03-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20240305_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_resources',
            field=models.ManyToManyField(blank=True, to='polls.Resource'),
        ),
    ]
