# Generated by Django 3.2.5 on 2024-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user_completed_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='study_method',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time_plan',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='carry_forward_reflection',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='study_method_reflection',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='time_reflection',
            field=models.CharField(max_length=4000),
        ),
    ]
