# Generated by Django 3.2.5 on 2024-04-10 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20240410_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reflection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
